POST http://localhost:5000/api/rents HTTP/1.1
Content-Type: application/json

{
    "movieId": 2,
    "userId": 3,
    "deadline": "2024-03-10"
}


# {
#     "movie": "65e489af0c367d966440fdcf",
#     "user": "65e48aa50c367d966440fdd2"
# }

